### ISSUE TITLE
Broken Pipe when piping output

### ISSUE THREAD

**Issue by benwilber** [hoffa/kitten#15]
Hello, very nice tool!  I occasionally (not every time) get a broken pipe error when piping output:

```
$ kitten ip --region us-east-2 asg --public <ASG NAME> | head -1
<REDACTED PUBLIC IP>
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 996, in emit
    self.flush()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 976, in flush
    self.stream.flush()
BrokenPipeError: [Errno 32] Broken pipe
Call stack:
  File "/Users/benw/.virtualenvs/kitten/bin/kitten", line 11, in <module>
    sys.exit(main())
  File "/Users/benw/.virtualenvs/kitten/lib/python3.6/site-packages/kitten/__init__.py", line 255, in main
    ip(args.values, args.kind, args.public, args.region)
  File "/Users/benw/.virtualenvs/kitten/lib/python3.6/site-packages/kitten/__init__.py", line 106, in ip
    print_ips(ec2, instance_ids, public, region_name)
  File "/Users/benw/.virtualenvs/kitten/lib/python3.6/site-packages/kitten/__init__.py", line 93, in print_ips
    log.info(public and ip["public"] or ip["private"])
Message: '<REDACTED PUBLIC IP>'
Arguments: ()
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Python 3.6.5 on macOS with Kitten 0.2.4

**Comment by hoffa** [comment]
Thanks for the report!
Seems that Python [ignores SIGPIPE](https://docs.python.org/3/library/signal.html#general-rules), which turns into an exception. I've added the default signal handler for SIGPIPE, which should correspond to expected command-line tool behavior.
I've pushed 0.2.5, let me know if you have any issues!

**Comment by hoffa** [comment]
I'll close this for now since it shouldn't throw on SIGPIPE anymore.
